// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    voting_contract
    (
        init => init
        upgrade => upgrade
        getCandidates => candidates
        getVoters => voters
        getVotes => votes
        add_candidate => add_candidate
        register_voter => register_voter
        vote => vote
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
